version: "3.8"

services:
  discovery:
    container_name: eureka-server
    build:
      context: ./eureka-server
      dockerfile: Dockerfile
    ports:
      - "8761:8761"

  gateway:
    container_name: secured-gateway
    build:
      context: ./secured-gateway
      dockerfile: Dockerfile
    environment: 
      SPRING_DATASOURCE_URL: ${GATEWAY_SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${GATEWAY_MYSQL_USER}
      SPRING_DATASOURCE_PASSWORD: ${GATEWAY_MYSQL_PASSWORD}
      SPRING_DATASOURCE_INITIALIZATION-MODE: ${GATEWAY_SPRING_DATASOURCE_INITIALIZATION}
      SPRING_JPA_HIBERNATE_DDL-AUTO: ${GATEWAY_SPRING_JPA_HIBERNATE_DLL}
      eureka.client.serviceUrl.defaultZone: http://discovery:8761/eureka/
    ports:
      - "8762:8762"
    depends_on:
      - discovery
      - gateway-db
    links:
      - discovery:discovery
      - gateway-db
    command: ["../wait.sh", "customers-db:3306"]

  gateway-db:
    container_name: secured-gateway-db
    image: mysql:5.7
    platform: linux/amd64
    restart: always
    environment:
      MYSQL_DATABASE: ${GATEWAY_MYSQL_DATABASE}
      MYSQL_USER: ${GATEWAY_MYSQL_USER}
      MYSQL_PASSWORD: ${GATEWAY_MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${GATEWAY_MYSQL_ROOT_PASSWORD}
    ports:
      - '33060:3306'
    expose:
      - '33060'
    volumes:
      - ${GATEWAY_MYSQL_VOLUME}:/var/lib/mysql

  customers:
    container_name: customers-service
    build:
      context: ./customers-service
      dockerfile: Dockerfile
    environment: 
      SPRING_DATASOURCE_URL: ${CUSTOMER_SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${CUSTOMER_MYSQL_USER}
      SPRING_DATASOURCE_PASSWORD: ${CUSTOMER_MYSQL_PASSWORD}
      SPRING_DATASOURCE_INITIALIZATION-MODE: ${CUSTOMER_SPRING_DATASOURCE_INITIALIZATION}
      SPRING_JPA_HIBERNATE_DDL-AUTO: ${CUSTOMER_SPRING_JPA_HIBERNATE_DLL}
      eureka.client.serviceUrl.defaultZone: http://discovery:8761/eureka/
    ports:
      - "8200:8200"
    depends_on:
      - discovery
      - gateway
      - customers-db
    links:
      - discovery:discovery
      - customers-db
    command: ["../wait.sh", "customers-db:3306"]

  customers-db:
    container_name: customers-service-db
    image: mysql:5.7
    platform: linux/amd64
    restart: always
    environment:
      MYSQL_DATABASE: ${CUSTOMER_MYSQL_DATABASE}
      MYSQL_USER: ${CUSTOMER_MYSQL_USER}
      MYSQL_PASSWORD: ${CUSTOMER_MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${CUSTOMER_MYSQL_ROOT_PASSWORD}
    ports:
      - '33061:3306'
    expose:
      - '33061'
    volumes:
      - ${CUSTOMER_MYSQL_VOLUME}:/var/lib/mysql

  frontend:
    container_name: ui
    build:
      context: ./ui
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - discovery
      - gateway
      - customers-db
    links:
      - gateway
